### ISSUE TITLE
go get support?

### ISSUE THREAD

**Issue by toqueteos** [jasonroelofs/slartibartfast#1]
Why is everything inside the src folder?
Why there are bin and pkg folders with only a .gitkeep file?
What's so wrong for you to do a bunch of `go get -u repo` lines, or put those inside a bash file?

If you want to use some version of any of your dependencies inside Rakefile why don't you just fork those projects? Then use gofmt -r to rename import pahts and you are done.

**Comment by jasonroelofs** [comment]
This project is not intended to ever be "go get"-able. It's a full application and not a library. If / when I get to the point of distribution, I'll provide compiled packages people can download and run. If I find that some of the code can be used as a stand-alone library then it will get pulled out and treated as such in the normal Go way.

Please check out http://jasonroelofs.com/2013/08/01/application-development-in-go/ for the reasons why this repo is structured the way it is.

**Comment by toqueteos** [comment]
I came here just because of that blog post.

I myself I'm making use of almost the same libraries and got no problems using go get for making an application.

**Comment by jasonroelofs** [comment]
I had a feeling as such but didn't want to assume.

I'm glad you found a way that works for you. In my experience I don't feel that this pattern is conducive to long term deterministic application development, and that's why I wrote the post and have this repository structured as it is. Over time as the Go environment matures we'll see if I'm wrong or not about this and I will adjust accordingly.

Thanks for the feedback though, and I'll be sure to keep an eye on your projects and others I've seen around.
